/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElChcekbox: typeof import('element-plus/es')['ElChcekbox']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElChekbox: typeof import('element-plus/es')['ElChekbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Login: typeof import('./src/components/index/Login.vue')['default']
    Register: typeof import('./src/components/index/Register.vue')['default']
    ResetPwd: typeof import('./src/components/index/ResetPwd.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
