spring:
  rabbitmq:
    host: 123.249.98.26
    port: 5672
    virtual-host: dev
    username: guest
    password: guest
    listener:
      simple:
        # manual or auto
        acknowledgemode: auto
        retry:
          # Exception retry.
          enabled: true
          max-attempts: 4
          initial-interval: 4000
  # email
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtp
    default-encoding: UTF-8
    username: rainbowjie1@qq.com
    password: mcfsmexjhkwudgdb
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: true
        debug: true

# sms
sms:
  app-code: 3d82217b4f67418a969968d160a63559
  template-id: JM1000372

# sa-token
sa-token:
  token-name: loginToken
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-64
  # token 有效期（单位：秒） 默认2小时，-1 代表永久有效
  timeout: 7200
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # 是否输出操作日志
  is-log: false
token:
  # token 过期时间（单位：秒），7天
  expiresTime: 604800


# 图形验证码
captcha:
  # 图形验证码过期时间（十分钟），单位毫秒，
  expiredTime:600000
